
-- ---------------------------------------------------------------------------------------------  
--  
-- Purpose: Return Cntracts Details.  
--  
--    Date        Version    Who        Control        Comment  
-- ----------    -------    -------    -----------    ----------------------------------------------------  
-- 16/02/2023       V1       Manoj                   Initial Version  
-- 16/02/2023       V1       Manoj                   Added 'UID' logic for Uniqueness
-- 16/02/2023       V1       Manoj                   Added 'CRC' logic for Increamental
-- 31/12/2024       V4       Manish  
-- -----------------------------------------------------------------------------------------------
CREATE VIEW DatahubPMR.v_CONTRACT_RAW_DETAILS
AS 
WITH CONTRACT_RAW_DETAILS AS   
 (
SELECT Distinct
CONCAT([DATAHUB_ODESSA].[ODH].CONTRACTS.ID,'_',[DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS.ID,'_',[DATAHUB_ODESSA].[ODH].RECEIVABLES.ID,'_',[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.ID)              AS [UID],
[DATAHUB_ODESSA].[ODH].CONTRACTS.ID                                   AS CONT_ID,
[DATAHUB_ODESSA].[ODH].CONTRACTS.SEQUENCENUMBER                       AS CONT_SEQUENCENUMBER,
[DATAHUB_ODESSA].[ODH].LEASEFINANCES.BOOKINGSTATUS                    AS CONT_STATUS,
[DATAHUB_ODESSA].[ODH].LEASEFINANCES.ID                               AS LEASEFIN_ID,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.ID                                 AS REC_ID,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.INCOMETYPE                         AS REC_INCOMETYPE,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT                     AS REC_INVOICECOMMENT,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.RECEIVABLECODEID                   AS REC_RECEIVABLECODEID,
[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.ID                          AS RECINV_ID,
LEASEASSETS.ACTIVERESIDUALAMOUNT                                      AS LEASS_ACTIVERESIDUALAMOUNT,
LEASEASSETS.MAXTERMINATIONDATE                                        AS LEASS_MAXTERMINATIONDATE,
(CASE WHEN ISNULL([DATAHUB_ODESSA].[ODH].LEASEFINANCES.BOOKINGSTATUS,'')='FullyPaidOff' THEN 'Yes' ELSE 'No' END) AS CONT_TERMINATION_FLAG, 
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 30 AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 0 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_1_30,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 60 AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 30 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_31_60,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 90 AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 60 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_61_90,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 120 AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 90 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT +RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_91_120,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 150 AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 120 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_121_150,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 180 AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 150 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_151_180,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 360 AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 180 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_181_360,
(CASE WHEN ((DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 360 AND (DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 721  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_361_720,
(CASE WHEN ((DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 720 AND (DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 1081 ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_721_1080, 
(CASE WHEN (DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1080 THEN  ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_1080_Plus, 
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 180 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_181_Plus,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 360 ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_360_Plus,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 30 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
END)                                                 AS  "Age_30_Plus",
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 90 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_90_Plus,
(CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 150 THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
ELSE 0
END)                                                 AS Age_150_Plus,
(CASE WHEN ((DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1080 AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 1441  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_1081_1440,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1440 AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 1801  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_1441_1800,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1800 AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 2161  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_1801_2160,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 2160 ) THEN ( [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT ) ELSE 0 
END)                                                 AS Age_2160_Plus,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 180 AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 331  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_181_330,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 180 AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 301 ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_181_300,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 300 AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 331  ) THEN ( [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT ) ELSE 0 
END)                                                 AS Age_301_330,
(CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 330 AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 361  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
END)                                                 AS Age_331_360,
DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) AS PAST_DUE_DAYS_Less_360,
DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE)) AS PAST_DUE_DAYS_Greater_360,
(CASE WHEN [DATAHUB_ODESSA].[ODH].RECEIVABLES.INCOMETYPE!='_' THEN RTRIM(LTRIM(SUBSTRING(LTRIM(REPLACE(REPLACE([DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT,'FROM',''),'TO','|')),0,
CHARINDEX('|',LTRIM(REPLACE(REPLACE([DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT,'FROM',''),'TO','|'))))))
ELSE '' END)                                         AS RECINV_PERIOD_BEGIN_DATE,
(CASE WHEN [DATAHUB_ODESSA].[ODH].RECEIVABLES.INCOMETYPE!='_' THEN LTRIM(SUBSTRING(LTRIM(REPLACE(REPLACE([DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT,'FROM',''),'TO','|')),
CHARINDEX('|',LTRIM(REPLACE(REPLACE([DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT,'FROM',''),'TO','|')))+1,LEN(LTRIM(REPLACE(REPLACE([DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT,'FROM',''),'TO','|')))))
ELSE '' END)                                         AS RECINV_PERIOD_END_DATE,

HASHBYTES('MD5', CONCAT
                                    (                                   
                                           [DATAHUB_ODESSA].[ODH].CONTRACTS.ID,
                                           [DATAHUB_ODESSA].[ODH].CONTRACTS.SEQUENCENUMBER,                       
                                           [DATAHUB_ODESSA].[ODH].LEASEFINANCES.BOOKINGSTATUS,                              
                                           (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 30
					   AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 0
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 60
					   AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 30
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                 
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 90
					   AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 60
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 120
					   AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 90
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT +RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                 
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 150
					   AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 120
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                 
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 180
					   AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 150
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                 
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) < = 360
					   AND DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 180
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                 
					   (CASE WHEN ((DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 360 
					   AND (DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 721  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                 
					   (CASE WHEN ((DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 720 
					   AND (DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 1081 ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                 
					   (CASE WHEN (DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1080
					   THEN  ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
				           END),                                                  
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 180
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 360 ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 30
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   END),
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 90
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                 
					   (CASE WHEN DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)) > 150
					   THEN SUM(RECEIVABLEINVOICEDETAILS.EFFECTIVEBALANCE_AMOUNT + RECEIVABLEINVOICEDETAILS.EFFECTIVETAXBALANCE_AMOUNT)
					   ELSE 0
					   END),                                                 
					   (CASE WHEN ((DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1080
					   AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 1441  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1440
        				   AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 1801  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                 
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 1800
					   AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 2161  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 2160 ) THEN ( [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT ) ELSE 0 
					   END),                                                 
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 180
					   AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 331  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                 
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 180
					   AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 301 ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 300
					   AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 331  ) THEN ( [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT ) ELSE 0 
					   END),                                                
					   (CASE WHEN ((DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) > 330
					   AND (DATEDIFF(DAY, [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE))) < 361  ) THEN ([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT) ELSE 0 
					   END),                                                 
					   DATEDIFF(DAY, DATEADD(DD,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE), CAST(GETDATE() AS DATE)), 
     					   DATEDIFF(DAY,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE, CAST(GETDATE() AS DATE)),
                                           [DATAHUB_ODESSA].[ODH].RECEIVABLES.INCOMETYPE,
					   [DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT,
					   LEASEASSETS.ACTIVERESIDUALAMOUNT,
                                           LEASEASSETS.MAXTERMINATIONDATE 
                                                                           ))    AS CRC,
CONVERT(DATETIME,(SELECT MAX(T.UPDATEDTIME)  FROM (  
          VALUES( ISNULL([DATAHUB_ODESSA].[ODH].LEASEFINANCES.UPDATEDTIME,[DATAHUB_ODESSA].[ODH].LEASEFINANCES.CREATEDTIME)),  
            ( ISNULL([DATAHUB_ODESSA].[ODH].CONTRACTS.UPDATEDTIME,[DATAHUB_ODESSA].[ODH].CONTRACTS.CREATEDTIME)),  
            ( ISNULL([DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS.UPDATEDTIME,[DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS.CREATEDTIME)),  
            ( ISNULL([DATAHUB_ODESSA].[ODH].LEGALENTITIES.UPDATEDTIME,[DATAHUB_ODESSA].[ODH].LEGALENTITIES.CREATEDTIME)),  
            ( ISNULL([DATAHUB_ODESSA].[ODH].RECEIVABLES.UPDATEDTIME,[DATAHUB_ODESSA].[ODH].RECEIVABLES.CREATEDTIME))  ,
            ( ISNULL([DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.UPDATEDTIME,[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.CREATEDTIME))  
            ) AS T( UPDATEDTIME )))   
                                                                                 AS [USERMODIFIEDTIMESTAMP],
GETDATE()                                                                        AS LASTREFRESHTIME

FROM
[DATAHUB_ODESSA].[ODH].CONTRACTS(NOLOCK)
INNER JOIN
[DATAHUB_ODESSA].[ODH].LEASEFINANCES(NOLOCK) ON [DATAHUB_ODESSA].[ODH].LEASEFINANCES.CONTRACTID=[DATAHUB_ODESSA].[ODH].CONTRACTS.ID AND [DATAHUB_ODESSA].[ODH].LEASEFINANCES.ISCURRENT=1
INNER JOIN
[DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS(NOLOCK) ON [DATAHUB_ODESSA].[ODH].LEASEFINANCES.ID=[DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS.ID
INNER JOIN
[DATAHUB_ODESSA].[ODH].LEGALENTITIES(NOLOCK) ON [DATAHUB_ODESSA].[ODH].LEGALENTITIES.ID=[DATAHUB_ODESSA].[ODH].LEASEFINANCES.LEGALENTITYID
LEFT OUTER JOIN
(
SELECT  SEQUENCENUMBER,SUM(TAXAMOUNT_AMOUNT) AS TAXAMOUNT_AMOUNT,SUM(EFFECTIVEBALANCE_AMOUNT) AS EFFECTIVEBALANCE_AMOUNT,SUM(EFFECTIVETAXBALANCE_AMOUNT) AS EFFECTIVETAXBALANCE_AMOUNT,RECEIVABLEID,RECEIVABLEINVOICEID
 FROM [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICEDETAILS(NOLOCK) GROUP BY SEQUENCENUMBER,RECEIVABLEID,RECEIVABLEINVOICEID
)RECEIVABLEINVOICEDETAILS ON RECEIVABLEINVOICEDETAILS.SEQUENCENUMBER=[DATAHUB_ODESSA].[ODH].CONTRACTS.SEQUENCENUMBER
LEFT OUTER JOIN
[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES(NOLOCK) ON [DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.ID=RECEIVABLEINVOICEDETAILS.RECEIVABLEINVOICEID
LEFT OUTER JOIN
[DATAHUB_ODESSA].[ODH].RECEIVABLES(NOLOCK) ON [DATAHUB_ODESSA].[ODH].RECEIVABLES.ID=RECEIVABLEINVOICEDETAILS.RECEIVABLEID
LEFT OUTER JOIN
(
SELECT LEASEFINANCEID , SUM(CASE WHEN ISACTIVE=1 THEN BOOKEDRESIDUAL_AMOUNT END) as ACTIVERESIDUALAMOUNT,
        MAX(CASE WHEN ISACTIVE=0 THEN TERMINATIONDATE END) AS MAXTERMINATIONDATE
FROM [DATAHUB_ODESSA].[ODH].LEASEASSETS(NOLOCK)  GROUP BY LEASEFINANCEID
)LEASEASSETS ON LEASEASSETS.LEASEFINANCEID=[DATAHUB_ODESSA].[ODH].LEASEFINANCES.ID
GROUP BY
[DATAHUB_ODESSA].[ODH].CONTRACTS.ID,
[DATAHUB_ODESSA].[ODH].CONTRACTS.SEQUENCENUMBER,
[DATAHUB_ODESSA].[ODH].LEASEFINANCES.BOOKINGSTATUS,
[DATAHUB_ODESSA].[ODH].CONTRACTS.UPDATEDTIME,
[DATAHUB_ODESSA].[ODH].CONTRACTS.CREATEDTIME,
[DATAHUB_ODESSA].[ODH].LEASEFINANCES.ID,
[DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS.ID,
[DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS.UPDATEDTIME,
[DATAHUB_ODESSA].[ODH].LEASEFINANCEDETAILS.CREATEDTIME,
[DATAHUB_ODESSA].[ODH].LEASEFINANCES.UPDATEDTIME,
[DATAHUB_ODESSA].[ODH].LEASEFINANCES.CREATEDTIME,
[DATAHUB_ODESSA].[ODH].LEGALENTITIES.THRESHOLDDAYS,
[DATAHUB_ODESSA].[ODH].LEGALENTITIES.UPDATEDTIME,
[DATAHUB_ODESSA].[ODH].LEGALENTITIES.CREATEDTIME,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.ID,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.INVOICECOMMENT,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.INCOMETYPE,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.RECEIVABLECODEID, 
[DATAHUB_ODESSA].[ODH].RECEIVABLES.UPDATEDTIME,
[DATAHUB_ODESSA].[ODH].RECEIVABLES.CREATEDTIME,
[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.ID,
[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.BALANCE_AMOUNT,
[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.DUEDATE,
[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.UPDATEDTIME,
[DATAHUB_ODESSA].[ODH].RECEIVABLEINVOICES.CREATEDTIME,
RECEIVABLEINVOICEDETAILS.TAXAMOUNT_AMOUNT,
LEASEASSETS.ACTIVERESIDUALAMOUNT,
LEASEASSETS.MAXTERMINATIONDATE

)

SELECT CRD.* FROM CONTRACT_RAW_DETAILS CRD LEFT OUTER JOIN [DatahubPMR].[CONTRACT_RAW_DETAILS](NOLOCK) CRDS ON CRD.[UID]=CRDS.[UID] WHERE 1=CASE
                                                                        WHEN CRDS.CRC IS NULL THEN 1 
                                                                        WHEN CRDS.CRC IS NOT NULL AND CRD.CRC != CRDS.CRC  THEN 1
                                                                        ELSE 0
                                           END

