/*DBTYPE:SQLSERVER|TARGETDB:HPFSIDS*/

IF EXISTS (SELECT * FROM SYS.SYNONYMS WHERE NAME = N'[DIMN].[PP_ASSET_DETAIL_03]')
BEGIN
    DROP SYNONYM [DIMN].[PP_ASSET_DETAIL_03]
END
GO

CREATE SYNONYM [DIMN].[PP_ASSET_DETAIL_03] FOR [FCT_20210430].[PP_CHILD_ASET_DTL]


GO
GRANT EXECUTE ON [DIMN].[PP_ASSET_DETAIL_03] TO DMUsr01;
GO
